### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by acroz** [CoxAutomotiveDataSolutions/waimak#13]
Hi,

Waimak looks like a great tool that I'm interested in learning more about. In your README there's a documentation link, but that takes me to an empty GitHub wiki. Is there some API documentation or examples somewhere I can look at to learn how to use Waimak? Sorry if I've missed something obvious.

Thanks!

**Comment by alexjbush** [comment]
Hi Andrew,

Thanks for the interest. Unfortunately, the link in the README is correct but there is no public documentation yet. We're working on putting some together in the coming weeks and it will be on the GitHub wiki.
I'll leave this issue and close it off once it has been released!

Thanks

**Comment by alexjbush** [comment]
@acroz  We have been slowly adding documentation to the wiki at: [https://github.com/CoxAutomotiveDataSolutions/waimak/wiki](https://github.com/CoxAutomotiveDataSolutions/waimak/wiki)

I think we have enough documentation to close this issue now. Happy for it to be reopened if there are any particular areas missing.
