### ISSUE TITLE
Actions that do not run should produce an error at the end of a flow by default instead of silently not running

### ISSUE THREAD

**Issue by alexjbush** [CoxAutomotiveDataSolutions/waimak#4]
## Expected Behavior
If you have a flow `a -> b -> c`, with action c depending on an output of b, if `b` produces an `None` output then `c` will not run. 

## Actual Behavior
However, this is often not what we want to happen and could indicate an error.  By default, if there are any actions left at the end of the flow that have not run then an exception should be thrown. It should also be possible to override this behaviour and mark an action as optional.

## Specifications

  - Waimak Module: Core

**Comment by alexeipab** [comment]
May be to add some sort of Policy object/function, that will handle it and will decide weather an exception is needed? There might be a case in the future when partial run is needed, with multiple restarts from, meaning that this partial run will have plenty of actions that were not executed yet.
