### ISSUE TITLE
ParquetDataCommitter fails when performing listStatus on the output directory if it does not exist

### ISSUE THREAD

**Issue by vavison** [CoxAutomotiveDataSolutions/waimak#55]
## Expected Behavior
`listStatus` is performed as part of the snapshot cleanup mechanism (to identify existing snapshots). If the output directory does not exist, the list of existing snapshots should be empty 

## Actual Behavior
The application will fail if the output directory is empty (i.e. the first time an application is run)

**Comment by alexjbush** [comment]
Not an issue
